---
- file: path=/var/www/swagger-ui state=directory

- git: repo=https://github.com/swagger-api/swagger-ui.git
       dest=/var/www/swagger-ui
       version=v2.1.4

- file: path=/var/www/html/swagger state=link src=/var/www/swagger-ui/dist
