---
- name: save iptables
  command: service iptables save
  notify: restart iptables
               
- name: restart iptables
  service: name=iptables state=restarted
               
- name: reload iptables
  service: name=iptables state=reloaded

- name: restart nrpe
  service: name=nrpe state=restarted

- name: reload nrpe
  service: name=nrpe state=reloaded

- name: restart rsyslog
  service: name=rsyslog state=restarted

- name: reload rsyslog
  service: name=rsyslog state=reloaded

- name: restart fail2ban
  service: name=fail2ban state=restarted

- name: reload fail2ban
  service: name=fail2ban state=reloaded

- name: restart sshd
  service: name=sshd state=restarted

- name: reload sshd
  service: name=sshd state=reloaded

- name: restart ntpd
  service: name=ntpd state=restarted
