---
- name: save iptables
  command: service iptables save
  notify: restart iptables
               
- name: restart iptables
  service: name=iptables state=restarted

- name: merge haproxy config
  assemble: "src=/etc/haproxy/conf.d/ dest=/etc/haproxy/haproxy.cfg delimiter='### START FRAGMENT ###'"
  notify: restart haproxy

- name: restart haproxy
  service: name=haproxy state=restarted

- name: restart tomcat
  service: name=tomcat state=restarted
