---
- name: save iptables
  command: service iptables save
  notify: restart iptables
               
- name: restart iptables
  service: name=iptables state=restarted

- name: restart httpd
  service: name=httpd state=restarted

- name: restart nagios
  service: name=nagios state=restarted
