---
# This role conains tasks for servers reboot in rolling manner

- name: rebooting server
  command: /sbin/shutdown -r now
  tags: reboot

- name: waiting for port after reboot
  wait_for: host={{ ansible_default_ipv4.address }} port={{ rolling_reboot_wait_port }} delay={{ _rolling_reboot.wait_delay }} state=started
  connection: local
  become: false
  tags: reboot

- name: pausing
  pause: minutes={{ rolling_reboot_pause }}
  tags: reboot
