---
- name: iptables internal
  command: /sbin/iptables -I INPUT 1 -s {{ subnet }}.0/16 -p tcp --dport {{ item.port }} -j ACCEPT -m comment --comment "ansible-{{ item.name }}-{{ item.port }}"
  when: iptablesrules.stdout.find("ansible-{{ item.name }}-{{ item.port }}") == -1
  notify: save iptables
  with_items:
      - { name: 'ldm', port: 388 }
  tags: iptables
