---
- name: iptables internal
  command: /sbin/iptables -I INPUT 1 -s {{ subnet }}.0/24 -p tcp --dport {{ item.port }} -j ACCEPT -m comment --comment "ansible-{{ item.name }}-{{ item.port }}"
  when: iptablesrules.stdout.find("ansible-{{ item.name }}-{{ item.port }}") == -1
  notify: save iptables
  with_items:
      - { name: 'data/dqm', port: 5000 }
  tags: iptables

- name: iptables external
  command: /sbin/iptables -I INPUT 1 -p tcp --dport {{ item.port }} -j ACCEPT -m comment --comment "ansible-{{ item.name }}-{{ item.port }}"
  when: iptablesrules.stdout.find("ansible-{{ item.name }}-{{ item.port }}") == -1
  notify: save iptables
  with_items:
      - { name: 'haproxy', port: 80 }
      - { name: 'haproxy-ssl', port: 443 }
      - { name: 'rwis/dqm/external', port: 30001 }
      - { name: 'image/dqm/external', port: 40001 }
  tags: iptables
