---
- name: restart haproxy
  service: name=haproxy state=restarted

- name: merge haproxy config
  assemble: "src=/etc/haproxy/conf.d/ dest=/etc/haproxy/haproxy.cfg delimiter='### START FRAGMENT ###'"
  notify: restart haproxy

- name: save iptables
  command: service iptables save
  notify: restart iptables
               
- name: restart iptables
  service: name=iptables state=restarted

- name: reload nrpe
  service: name=nrpe state=reloaded

- name: restart keepalived
  service: name=keepalived state=restarted

- name: reload keepalived
  service: name=keepalived state=reloaded

- name: restart httpd
  service: name=httpd state=restarted

- name: reload httpd
  service: name=httpd state=reloaded

