---
- name: restart haproxy
  service: name=haproxy state=restarted

- name: reload haproxy
  service: name=haproxy state=reloaded

- name: merge haproxy config
  assemble: "src=/etc/haproxy/conf.d/ dest=/etc/haproxy/haproxy.cfg delimiter='### START FRAGMENT ###'"
  notify: restart haproxy
