---
# defaults file for ansible-rolling-reboot playbook

# number of minutes to wait before next server reboot
rolling_reboot_pause: 1

# by default wait for ssh daemon after reboot
rolling_reboot_wait_port: 22

### Constants

_rolling_reboot:

  # wait 60 seconds before starting to poll
  wait_delay: 60
